---
title: "webifier Statistics"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    logo: webifier-small.png
    favicon: webifier-small.png
    css: style.css
    vertical_layout: fill 
    navbar:
      - { title: "webifier", href: "https://webifier.de/", align: right }
params:
  dbname: webifier_v1-SNAPSHOT

---

```{r setup, include=FALSE}
#Colors:      
COL.MALICIOUS<-"#d3061a"
COL.SUSPICIOUS<-"#ff8833"
COL.CLEAN<-"#007d25"
COL.UNDEFINED<-"#e1e1e1"
usePackage <- function(p)
{
  if (!is.element(p, installed.packages()[,1]))
    install.packages(p, repos='http://cran.r-project.org', dep = TRUE)
}
usePackage('flexdashboard')
usePackage('RMongo')
usePackage('RJSONIO')
usePackage('plotly')
usePackage('ggplot2')
usePackage('urltools')
usePackage('DT')
library('flexdashboard')
library('urltools')
library('RMongo')
library('RJSONIO')
library('plotly')
library('ggplot2')
library('DT')
mg1 <- mongoDbConnect(params$dbname)
print(dbShowCollections(mg1))
```

Dashboard
=====================================

Row {data-height=100}
-----------------------------------------------------------------------

### analysierte Webseiten

```{r}
resultType <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{}", "{overallResultType:1}",skip=0,limit=Inf)
valueBox(nrow(resultType), icon="fa-bar-chart",color="primary")
```

### saubere Webseiten

```{r}
value <- nrow(resultType[resultType$overallResultType=='CLEAN',])
base <- nrow(resultType)
gauge(value, min = 0, max = base, label = paste(round((value/base)*100),"%",sep=""), gaugeSectors(
  success = c(0, base), warning = c(-10, -5), danger = c(-4, -1)
))
```

### verdächtige Webseiten

```{r}
value <- nrow(resultType[resultType$overallResultType=='SUSPICIOUS',])
base <- nrow(resultType)
gauge(value, min = 0, max = base, label = paste(round((value/base)*100),"%",sep=""), gaugeSectors(
  success = c(-10, -5), warning = c(0, base), danger = c(-4, -1)
))
```

### bedrohliche Webseiten

```{r}
value <- nrow(resultType[resultType$overallResultType=='MALICIOUS',])
base <- nrow(resultType)
gauge(value, min = 0, max = base, label = paste(round((value/base)*100),"%",sep=""), gaugeSectors(
  success = c(-4, -1), warning = c(-10, -5), danger = c(0, base)
))
```

### Durchschnittliche Analysezeit

```{r}
result <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{}", "{durationInMillis:1}",skip=0,limit=Inf)
mean.dur <- mean(result$durationInMillis)/1000
mean.dur <- round(mean.dur)
valueBox(paste(mean.dur,'s',sep=""), icon="fa-hourglass-half",color="grey")
```

Row
-----------------------------------------------------------------------

Gesamtauswertungen
=====================================

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Testergebnisverteilung

```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{}", '{_id:0,name:1,result:1}',skip=0,limit=Inf)
result <- result[,-1]
result[result$result=='MALICIOUS',2] <- "bedrohlich"
result[result$result=='SUSPICIOUS',2] <- "verdächtig"
result[result$result=='CLEAN',2] <- "sauber"
result[result$result=='UNDEFINED',2] <- "unbekannt"
names(result) <- c('Testname','Ergebnis')
p <- ggplot(data = result, aes(x = Testname, fill = Ergebnis)) +
            geom_bar(position = "dodge") +
            ylab("Anzahl") + 
  scale_fill_manual(values=c(COL.MALICIOUS,COL.CLEAN,COL.UNDEFINED,COL.SUSPICIOUS))
ggplotly(p)

```

### Erkennungen anhand Top-Level-Domains

```{r}
result <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{}", "{host:1,overallResultType:1}",skip=0,limit=Inf)
result[,1] <- tld_extract(result[,1],NULL)[,2]
result <- result[result[,2]!="CLEAN",]
result[result$overallResultType=='MALICIOUS',2] <- "bedrohlich"
result[result$overallResultType=='SUSPICIOUS',2] <- "verdächtig"
result[result$overallResultType=='UNDEFINED',2] <- "unbekannt"
names(result) <- c('TLD','Ergebnis','id')
p <- ggplot(data = result, aes(x = TLD, fill = Ergebnis),col="Anzahl") +
            geom_bar(position = "dodge") +
            ylab("Anzahl") + 
  scale_fill_manual(values=c(COL.MALICIOUS,COL.UNDEFINED,COL.SUSPICIOUS))
ggplotly(p)

```

### prozentuale Erkennungen anhand Top-Level-Domains

```{r}
result <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{}", "{host:1,overallResultType:1}",skip=0,limit=Inf)
result[,1] <- tld_extract(result[,1],NULL)[,2]
result <- result[result[,2]!="CLEAN",]
result[result$overallResultType=='MALICIOUS',2] <- "bedrohlich"
result[result$overallResultType=='SUSPICIOUS',2] <- "verdächtig"
result[result$overallResultType=='UNDEFINED',2] <- "unbekannt"
names(result) <- c('TLD','Ergebnis','Anzahl')
mal.result <-result[result$Ergebnis=='bedrohlich',]
susp.result <- result[result$Ergebnis=='verdächtig',]
und.result <- result[result$Ergebnis=='unbekannt',]
p <- plot_ly(alpha = 0.6) %>%
  add_histogram(x = ~mal.result$TLD, text="bedrohlich") %>%
  add_histogram(x = ~susp.result$TLD, text="verdächtig") %>%
  #add_histogram(x = ~und.result$TLD,text="unbekannt") %>%
  layout(barmode = "stack", title="Prozentuale Erkennungen anhand Top-Level-Domains")
ggplotly(p)

```

### Verteilung der getesteten Top-Level-Domains

```{r}
result <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{}", "{host:1,overallResultType:1}",skip=0,limit=Inf)
result[,1] <- tld_extract(result[,1],NULL)[,2]
names(result) <- c('TLD','Anzahl','pct')
result <- aggregate(Anzahl ~ TLD,result,length)
tld_sum <- sum(result$Anzahl)
result$pct <- 0.05
for(i in 1:nrow(result)) {
    result[i,3] <- result[i,2] / tld_sum
}
result[result$pct<0.007,1] <- 'Andere'
result <- result[,-3]
result <- aggregate(Anzahl ~ TLD,result,sum)

p <- plot_ly(result, labels = ~TLD, values = ~Anzahl, type = 'pie') %>%
  layout(title = 'Verteilung der getesteten Top-Level-Domains',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

ggplotly(p)
```


Virusscan {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'VirusScan'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```

Portscan {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'PortScan'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```

IPScan {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'IpScan'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```


PhishingDetector {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'PhishingDetector'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```


HeaderInspection {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'HeaderInspection'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```

LinkChecker {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'LinkChecker'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```

GoogleSafeBrowsing {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'GoogleSafeBrowsing'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```

CertificateChecker {data-navmenu="Einzelauswertungen"}
=====================================

Row
-----------------------------------------------------------------------

### Getestete Seiten
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierSingleTestResultData',"{name:'CertificateChecker'}", '{result:1}',skip=0,limit=Inf)
valueBox(nrow(result), icon="fa-bar-chart")
```

Row
-----------------------------------------------------------------------

### Ergebnisverteilung
```{r}
names(result)[2] <- "Anzahl"
result <- aggregate(Anzahl ~ result,result,length)
result[result$result=='MALICIOUS',1] <- "bedrohlich"
result[result$result=='SUSPICIOUS',1] <- "verdächtig"
result[result$result=='UNDEFINED',1] <- "unbekannt"
result[result$result=='CLEAN',1] <- "sauber"
p <- plot_ly(result, labels = ~result, values = ~Anzahl, type = 'pie',colors=c("red","darkgreen","grey","orange")) %>%
  layout(title = 'Ergebnisverteilung',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
ggplotly(p)
```

Die Top 100 der bedrohlichsten Webseiten
=====================================
```{r}
result <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{overallResultType:'MALICIOUS'}", '{host:1,overallResultValue:1}',skip=0,limit=Inf)
result <- result[order(result$overallResultValue,decreasing = TRUE),]
result <- head(result,100)
result$overallResultValue <- 1:nrow(result)
names(result) <- c('host','Rang')
datatable(result[,c(2,1)], options = list(pageLength = 10))
```

Ergebnisse durchsuchen
=====================================

Row
-----------------------------------------------------------------------
### alle Testergebnisse

```{r}
result <- dbGetQueryForKeys(mg1, 'webifierTestResultData',"{}", "{datetime:1,host:1,overallResultType:1}",skip=0,limit=Inf)
result <- result[,-4]
names(result) <- c('Datum','Domain','Ergebnis')
locale <- Sys.setlocale("LC_TIME", "en_US.UTF-8")
format <- "%a %b %d %H:%M:%S CEST %Y"
result[,1] <- format(as.Date(as.POSIXct(result[,1],format, tz="CET")),"%d-%m-%Y")
datatable(result, options = list(pageLength = 100))
```


